source 'https://rubygems.org'

gem 'rails'
gem 'vendoredlib2', :path => './vendor/ruby_lib.1'

gem 'rspec', :require => 'spec'
gem 'sqlite3', :require => false

gem 'kaminari', :git => 'https://github.com/kaminari/kaminari.git'
gem 'vendoredlib', :path => './vendor/ruby_lib'
gem 'metamagic', :git => 'https://github.com/lassebunk/metamagic.git', :platforms => [:ruby, :jruby]

gem 'wirble', :group => [:development, :test]

group :test do
  gem 'thin',  '~>1.1'
end