# Testcase: osinfo_example.tar
#
# To Build:
#   docker build -f Dockerfile.osinfo.sample . -t osinfo_example:latest
#
# To Export:
#   docker save osinfo_example:latest > osinfo_example.tar
#
# To Run:
#   docker run -it osinfo_example:latest /bin/sh
FROM busybox

# Generate fake os-release file
RUN echo "NAME=\"Fake OS\"" > /etc/os-release && \
    echo "VERSION=\"1.0\"" >> /etc/os-release && \
    echo "ID=fakeos" >> /etc/os-release && \
    echo "VERSION_ID=\"1.0\"" >> /etc/os-release && \
    echo "PRETTY_NAME=\"Fake OS 1.0\"" >> /etc/os-release