# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
inheritance: true
reviews:
  request_changes_workflow: true
  high_level_summary: false
  review_status: false
  commit_status: false
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false
chat:
  integrations:
    jira:
      usage: disabled
    linear:
      usage: disabled
