builds:
  - main: ./cmd/fossa/
    binary: fossa
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X github.com/fossas/fossa-cli/cmd/fossa/version.version={{.Version}} -X github.com/fossas/fossa-cli/cmd/fossa/version.commit={{.Commit}} -X "github.com/fossas/fossa-cli/cmd/fossa/version.goversion={{.Env.GOVERSION}}" -X github.com/fossas/fossa-cli/cmd/fossa/version.buildType=production
archive:
  format_overrides:
    - goos: windows
      format: zip
