builds:
  - main: ./cmd/fossa/
    binary: fossa
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -extldflags "-static" -s -w
      -X github.com/fossas/fossa-cli/cmd/fossa/version.version={{.Version}}
      -X github.com/fossas/fossa-cli/cmd/fossa/version.commit={{.Commit}}
      -X "github.com/fossas/fossa-cli/cmd/fossa/version.goversion={{.Env.GOVERSION}}"
      -X github.com/fossas/fossa-cli/cmd/fossa/version.buildType=release
archive:
  format_overrides:
    - goos: windows
      format: zip
release:
  prerelease: true
brews:
  -
    name: fossa
    description: "Fast, portable and reliable dependency analysis for any codebase. Supports license & vulnerability scanning for large monoliths. Language-agnostic; integrates with 20+ build systems."
    homepage: "https://fossa.com"

    github:
      owner: fossas
      name: homebrew-tap

    commit_author:
      name: fossabot
      email: engineering@fossa.com
