[package]
name = "rendergraph"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
color-eyre = "0.6.1"
eyre = "0.6.8"
petgraph = "0.6.0"
ptree = "0.4.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
colored = "2.0.0"
