FROM ghcr.io/fossas/haskell-dev-tools:8.10.4

WORKDIR /spectrometer
COPY app/ app/
COPY scripts/ scripts/
COPY integration-test/ integration-test/
COPY .hlint.yaml fourmolu.yaml Makefile spectrometer.cabal ./
COPY test/ test/
COPY src/ src/

RUN make check
