package report

import (
	"encoding/json"
	"fmt"
	"sort"
	"text/template"

	"github.com/apex/log"
	"github.com/urfave/cli"

	"github.com/fossas/fossa-cli/api/fossa"
	"github.com/fossas/fossa-cli/cmd/fossa/display"
	"github.com/fossas/fossa-cli/cmd/fossa/flags"
	"github.com/fossas/fossa-cli/cmd/fossa/setup"
	"github.com/fossas/fossa-cli/config"
	"github.com/fossas/fossa-cli/errors"
)

const defaultDependenciesReportTemplate = `# 3rd-Party Software Dependency List
Generated by fossa-cli (https://github.com/fossas/fossa-cli).
This project includes the following dependencies sorted by corresponding location:
{{range $license, $deps := .}}
========================================================================
{{$license}}
========================================================================
The following software has been found at this location:
{{range $i, $dep := $deps}}
- {{$dep.Project.Title}} - {{$dep.Locator.Revision}} - (from {{$dep.Project.URL}})
{{- end}}
{{end}}
`

var dependenciesCmd = cli.Command{
	Name:  "dependencies",
	Usage: "Generate dependencies report",
	Flags: flags.WithGlobalFlags(flags.WithAPIFlags(flags.WithOptions(flags.WithReportTemplateFlags([]cli.Flag{
		cli.BoolFlag{Name: JSON, Usage: "format output as JSON"},
	})))),
	Action: dependenciesRun,
}

func dependenciesRun(ctx *cli.Context) error {
	err := setup.SetContext(ctx)
	if err != nil {
		log.Fatalf("Could not initialize: %s", err.Error())
	}

	defer display.ClearProgress()
	display.InProgress(fmt.Sprint("Fetching Dependency Information"))

	locator := fossa.Locator{
		Fetcher:  config.Fetcher(),
		Project:  config.Project(),
		Revision: config.Revision(),
	}
	revs, err := fossa.GetRevisionDependencies(locator)
	if err != nil {
		return errors.Wrapf(err, "Unable to find dependencies for project %s:", locator)
	}

	if ctx.Bool(JSON) {
		output, err := json.Marshal(revs)
		if err != nil {
			return err
		}
		fmt.Println(string(output))
		return nil
	}

	revisionsByFetcher := make(map[string][]fossa.Revision)
	for _, rev := range revs {
		if len(rev.Locator.Fetcher) > 0 {
			revisionsByFetcher[rev.Locator.Fetcher] = append(revisionsByFetcher[rev.Locator.Fetcher], rev)
		}
	}

	// Sort the dependency lists alphabetically by Project Title.
	for fetcher, depList := range revisionsByFetcher {
		sort.Slice(depList[:], func(i, j int) bool {
			return depList[i].Project.Title < depList[j].Project.Title
		})
		revisionsByFetcher[fetcher] = depList
	}

	tmpl, err := template.New("base").Parse(defaultDependenciesReportTemplate)
	if err != nil {
		log.Fatalf("Could not parse template data: %s", err.Error())
	}

	output, err := display.Template(tmpl, revisionsByFetcher)
	fmt.Println(output)
	return err
}
