[package]
name = "millhone"
version = "0.4.0"
edition = "2021"

[features]
default = []
jemalloc = ["dep:tikv-jemallocator"]

[dependencies]
tikv-jemallocator = { version = "0.5.4", optional = true }
clap = { version = "4.3.21", features = ["derive", "env", "cargo"] }
stable-eyre = "0.2.2"
traceconf = { git = "https://github.com/fossas/foundation-libs", version = "1.1.0" }
serde = { version = "1.0.183", features = ["derive"] }
tracing = "0.1.37"
getset = "0.1.2"
typed-builder = "0.16.0"
tap = "1.0.1"
serde_json = "1.0.107"
atty = "0.2.14"
tracing-subscriber = { version = "0.3.20", features = ["json"] }
fingerprint = { git = "https://github.com/fossas/lib-fingerprint.git", tag = "v3.0.0", default-features = false, features = ["fp-content-serialize-base64"] }
tar = "0.4.45"
zip = "2.3.0"
flate2 = "1"

[dev-dependencies]
pretty_assertions = "1.4.0"
