# # fossa-cli configuration file.
# #
# # All fields are optional except 'version' field.
# #
# #  To learn more:
# #   - https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md
# #
# #  If you need assistance, or would like to file a defect, contact support at:
# #   - https://support.fossa.com/
# #
# # -----

version: 3
# server: https://app.fossa.com
# apiKey: a1b2c3
#
# project:
#   id: github.com/fossas/fossa-cli
#   name: fossa-cli
#   team: cli-team
#   policy: custom-cli-policy
#   link: fossa.com
#   url: github.com/fossas/fossa-cli
#   jiraProjectKey: jira-key
#   releaseGroup:
#     name: release-group-name
#     release: 123-release-candidate
#   labels:
#     - project-label-1
#     - test-project
#
# revision:
#   commit: "12345"
#   branch: master
#
# vendoredDependencies:
#   forceRescans: false
#   scanMethod: CLILicenseScan
#   licenseScanPathFilters:
#     only:
#       - "**/*.rb"
#     exclude:
#       - ".git/**"
#       - "test/**/*.rb"
#
# targets:
#   only:
#     - type: maven
#       path: foo/bar
#   exclude:
#     - type: bundler
#
# paths:
#   only:
#     - ./vendor/django
#     - ./test
#   exclude:
#     - ./vendor/django/test
#
# telemetry:
#   scope: full

# customLicenseSearch:
#   - matchCriteria: "[Pp]roprietary [Ll]icense"
#     name: "Proprietary License"

# experimentalKeywordSearch:
#   - matchCriteria: "[Pp]roprietary and [Cc]onfidential"
#     name: "Proprietary and Confidential match"
