{-# LANGUAGE RecordWildCards #-}

module Strategy.Conan.ConanGraph (
  ConanGraph (..),
  ConanGraphDependency (..),
  ConanGraphNode (..),
  ConanGraphNodeContext (..),
  buildGraph,
  analyzeFromConanGraph,
  toDependency,
)
where

import Control.Effect.Diagnostics (Diagnostics, errCtx, errHelp, run)
import Control.Monad (when)
import Data.Aeson (
  FromJSON (parseJSON),
  Key,
  Object,
  withObject,
  withText,
  (.:),
 )
import Data.Aeson.Extra (TextLike)
import Data.Aeson.Types (Parser)
import Data.Foldable (for_)
import Data.Map (Map, findWithDefault, keys, lookup, toList)
import Data.Map qualified as Map
import Data.Maybe (fromMaybe, mapMaybe)
import Data.Set qualified as Set
import Data.Text (Text)
import DepTypes (
  DepEnvironment (..),
  DepType (ConanType),
  Dependency (..),
  VerConstraint (CEq),
 )
import Diag.Diagnostic (ToDiagnostic (renderDiagnostic))
import Effect.Exec (
  AllowErr (Never),
  Command (..),
  Exec,
  Has,
  execJson,
 )
import Effect.Grapher (Grapher, deep, direct, edge, evalGrapher)
import Errata (Errata (..))
import Graphing (Graphing)
import Path (Abs, Dir, Path)
import Strategy.Conan.Version (guardConanVersion2Gt)

-- | Represents `conan graph info -f json`.
-- Creates the dependency graph for a conan project.
--
-- >> conan graph info -f json
-- >
-- > {
-- > "graph": {
-- >  "nodes": {
-- >    "0": {
-- >       "ref": "conanfile",
-- >       "id": 0,
-- >        ....
-- >    },
-- >  },
-- >  "root": {..}
-- > }
-- > }
conanV2GraphCmd :: [Text] -> Command
conanV2GraphCmd extraArgs =
  Command
    { cmdName = "conan"
    , cmdArgs = ["graph", "info", "-f", "json"] <> extraArgs
    , cmdAllowErr = Never
    , cmdEnvVars = Map.empty
    }

data ConanGraph = ConanGraph
  { nodes :: Map Text ConanGraphNode
  , root :: Map Text Text
  }
  deriving (Show, Eq, Ord)

instance FromJSON ConanGraph where
  parseJSON = withObject "ConanGraph" $ \obj ->
    ConanGraph
      <$> obj .: "graph" |> "nodes"
      <*> obj .: "graph" |> "root"
    where
      (|>) :: (FromJSON a) => Parser Object -> Key -> Parser a
      (|>) parser key = do
        obj <- parser
        obj .: key

data ConanGraphNode = ConanGraphNode
  { -- Node reference
    ref :: TextLike
  , -- Unique Node Id for this node in the graph
    nodeid :: TextLike
  , -- Signifies the package identifier, which
    -- is generated by combination of settings,
    -- options, and package name, package version.
    packageId :: Maybe Text
  , -- Title of the package
    name :: Maybe Text
  , -- Version of the package
    version :: Maybe Text
  , -- Context, refer to @ConanGraphNodeContext@
    context :: ConanGraphNodeContext
  , -- True if it is a test package, Otherwise False.
    test :: Bool
  , -- Dependencies
    dependencies :: Map Text ConanGraphDependency
  }
  deriving (Show, Eq, Ord)

instance FromJSON ConanGraphNode where
  parseJSON = withObject "ConanGraphNode" $ \obj -> do
    ConanGraphNode
      <$> obj .: "ref"
      <*> obj .: "id"
      <*> obj .: "package_id"
      <*> obj .: "name"
      <*> obj .: "version"
      <*> obj .: "context"
      <*> obj .: "test"
      <*> obj .: "dependencies"

data ConanGraphDependency = ConanGraphDependency
  { -- Dependency reference
    dep_ref :: TextLike
  , dep_test :: Bool
  , dep_direct :: Bool
  , dep_build :: Bool
  }
  deriving (Show, Eq, Ord)

instance FromJSON ConanGraphDependency where
  parseJSON = withObject "ConanGraphDependency" $ \obj -> do
    ConanGraphDependency
      <$> obj .: "ref"
      <*> obj .: "test"
      <*> obj .: "direct"
      <*> obj .: "build"

data ConanGraphNodeContext
  = -- The host context is populated with the root package
    -- (the one specified in the conan install or conan create command),
    -- all its requirements are of "host" context.
    HostContext
  | -- The build context contains the rest of build requirements
    -- and all of them in the profiles. This category typically includes
    -- all the dev tools like CMake, compilers, linkers.
    BuildContext
  | -- Other context. Conan as of v2.0.5 only has build and host context
    -- but this other context is added as saftey hatch, if in future
    -- additional context are added. Our parser should not fail outright
    -- if the context is not recognized.
    OtherContext Text
  deriving (Show, Eq, Ord)

instance FromJSON ConanGraphNodeContext where
  parseJSON = withText "Context" $ \ctx -> do
    case ctx of
      "host" -> pure HostContext
      "build" -> pure BuildContext
      other -> pure $ OtherContext other

getDirectDepsMap :: (Applicative m) => ConanGraph -> m (Map Text Bool)
getDirectDepsMap graph = do
  case Map.lookup "0" (nodes graph) of
    Nothing -> pure Map.empty
    Just node -> pure (Map.map dep_direct (dependencies node))

mkGraph :: (Has (Grapher Dependency) sig m) => ConanGraph -> m ()
mkGraph conanGraph = do
  directDeps <- getDirectDepsMap conanGraph
  for_ (toList $ nodes conanGraph) $ \(key, dep) -> do
    let resolvedDep = toDependency dep
    let isDirect = findWithDefault False key directDeps
    if isDirect
      then direct resolvedDep
      else deep resolvedDep

    let transitives = mapMaybe (refToDependency) (keys $ dependencies dep)
    let resolvedDirectDeps = Map.map dep_direct (dependencies dep)
    for_ transitives $ \(nodeId, childDep) -> do
      let isDirectChild = findWithDefault False nodeId resolvedDirectDeps
      when isDirectChild $ edge resolvedDep childDep
  where
    registry :: Map Text ConanGraphNode
    registry = nodes conanGraph

    refToDependency :: Text -> Maybe (Text, Dependency)
    refToDependency nodeId = ((nodeId,)) . toDependency <$> Data.Map.lookup nodeId registry

toDependency :: ConanGraphNode -> Dependency
toDependency cn =
  Dependency
    { dependencyType = ConanType
    , dependencyName = fromMaybe "root" (name cn)
    , dependencyVersion = Just (CEq $ fromMaybe "" (version cn))
    , dependencyLocations = []
    , dependencyEnvironments = Set.singleton $ getEnv cn
    , dependencyTags = mempty
    }

getEnv :: ConanGraphNode -> DepEnvironment
getEnv ConanGraphNode{..} = case (test, context) of
  (True, _) -> EnvTesting
  (_, BuildContext) -> EnvDevelopment
  (_, HostContext) -> EnvProduction
  _ -> EnvProduction

buildGraph :: ConanGraph -> Graphing Dependency
buildGraph conanGraph = run . evalGrapher $ mkGraph conanGraph

analyzeFromConanGraph :: (Has Exec sig m, Has Diagnostics sig m) => Path Abs Dir -> m (Graphing Dependency)
analyzeFromConanGraph dir = do
  -- We only support conan v2 or greater for this tactic,
  -- since, conan v1 does not have equiavlent command, which
  -- would ensure source code is always retrieved. Also, the
  -- equivalent command of "conan info ." in conan v1
  -- does not provide used settings for the dependency.
  errCtx ConanV2IsRequiredCtx $ errHelp ConanV2IsRequiredHelp $ guardConanVersion2Gt dir

  conanGraph <- execJson dir $ conanV2GraphCmd []
  pure $ buildGraph conanGraph

data ConanV2IsRequired
  = ConanV2IsRequiredCtx
  | ConanV2IsRequiredHelp

instance ToDiagnostic ConanV2IsRequired where
  renderDiagnostic ConanV2IsRequiredCtx = do
    let header = "Conan analysis requires conan v2.0.6 or greater"
    Errata (Just header) [] Nothing
  renderDiagnostic ConanV2IsRequiredHelp = do
    let header = "Ensure you are using conan v2 by running, conan --version"
    Errata (Just header) [] Nothing
